-- model_setting.id 를 자동 발번(identity)로 전환.
-- V4 는 단일행(id=1) 전제로 id 를 수동 INSERT 했으나, 멀티유저 전환(V12) 이후엔 신규 사용자마다
-- 자기 행이 필요하다 — id 발번 수단이 없으면 최초 설정(첫 PUT)에서 행을 만들 수 없다.
-- 기존 시드(id=1)와 충돌하지 않도록 시퀀스 시작값을 2 로 둔다(V12 가 단일행 id=1 을 이미 보장).
ALTER TABLE model_setting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2);
